name: adminor
description: Admin Manager App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  page_transition: ^2.0.9
  http: ^1.2.1
  smooth_page_indicator: ^1.0.0+2
  liquid_swipe: ^3.1.0
  mobkit_dashed_border: ^0.0.5
  chat_bubbles: ^1.5.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  get: ^4.6.6
  image_picker: ^1.0.7
  flutter_email_sender: ^6.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/




  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
        - asset: assets/fonts/Shabnam-Medium.ttf
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam-Medium.ttf
    - family: mont
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
