Map<String,bool> cities = {
  "آذربایجان شرقی": true,
  "آذربایجان غربی": false,
  "اردبیل": false,
  "اصفهان": false,
  "البرز": false,
  "ایلام": false,
  "بوشهر": false,
  "تهران": false,
  "چهارمحال و بختیاری": false,
  "خراسان جنوبی": false,
  "خراسان رضوی": false,
  "خراسان شمالی": false,
  "خوزستان": false,
  "زنجان": false,
  "سمنان": false,
  "سیستان و بلوچستان": false,
  "فارس": false,
  "قزوین": false,
  "قم": false,
  "کردستان": false,
  "کرمان": false,
  "کرمانشاه": false,
  "کهگیلویه و بویراحمد": false,
  "گلستان": false,
  "گیلان": false,
  "لرستان": false,
  "مازندران": false,
  "مرکزی": false,
  "هرمزگان": false,
  "همدان": false,
  "یزد":false,
};
